"""Initial schema with free_evenings String

Revision ID: 85c55ba1dad5
Revises: 
Create Date: 2026-09-26 00:49:38.907331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c55ba1dad5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_telegram_id'), 'candidates', ['telegram_id'], unique=True)
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_stack', sa.Text(), nullable=True),
    sa.Column('experience_min_years', sa.Integer(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screenings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('salary_expectation', sa.Integer(), nullable=True),
    sa.Column('relocation', sa.String(length=50), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('free_evenings', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'REJECTED', name='screeningstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'vacancy_id', name='uq_candidate_vacancy')
    )
    op.create_index(op.f('ix_screenings_candidate_id'), 'screenings', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_screenings_status'), 'screenings', ['status'], unique=False)
    op.create_index(op.f('ix_screenings_vacancy_id'), 'screenings', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenings_vacancy_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_status'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_candidate_id'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_candidates_telegram_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
