"""Add InterviewSlot model and link to Screening

Revision ID: 94efb581b90e
Revises: 85c55ba1dad5
Create Date: 2026-09-28 16:26:38.408410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94efb581b90e'
down_revision: Union[str, Sequence[str], None] = '85c55ba1dad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('max_slots', sa.Integer(), nullable=False),
    sa.Column('booked_slots', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_slots_date'), 'interview_slots', ['date'], unique=False)
    
    # Use batch operations for SQLite to add column and foreign key
    with op.batch_alter_table('screenings') as batch_op:
        batch_op.add_column(sa.Column('interview_slot_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_screenings_interview_slot_id'), ['interview_slot_id'], unique=False)
        batch_op.create_foreign_key('fk_screenings_interview_slot_id', 'interview_slots', ['interview_slot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenings') as batch_op:
        batch_op.drop_constraint('fk_screenings_interview_slot_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_screenings_interview_slot_id'))
        batch_op.drop_column('interview_slot_id')
    
    op.drop_index(op.f('ix_interview_slots_date'), table_name='interview_slots')
    op.drop_table('interview_slots')
    # ### end Alembic commands ###